# Generated by Django 5.1.6 on 2025-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skindiseasedetection',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
