# Generated by Django 5.1.6 on 2025-03-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_skindiseasedetection_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skindiseasedetection',
            name='severity',
        ),
    ]
